// SoundService — Phaser WebAudio sound engine, no canvas.
// Phaser.HEADLESS creates a game with no renderer; the WebAudio manager
// is fully functional. Audio files live in public/audio/{key}.webm|mp3.
//
// Usage:
//   SoundService.init()                     — call once in App.tsx on mount
//   SoundService.playSfx('hit')             — one-shot effect
//   SoundService.playMusic('battle_theme')  — looping background track
//   SoundService.stopMusic()
//   SoundService.setSfxVolume(0.8)
//   SoundService.setMusicVolume(0.5)

// Phaser is loaded dynamically inside init(). A top-level import would drag the
// whole engine into the module graph of every component that merely wants to
// play a blip — and Phaser's canvas feature probe throws outside a browser,
// which made the service unimportable from tests. Types are erased at compile
// time, so `import type` is free.
import type PhaserNS from 'phaser'
import { Capacitor } from '@capacitor/core'

// ── Registered audio keys ─────────────────────────────────────────────────────
// Add entries here as audio files land in public/audio/.

const SFX_KEYS: string[] = [
  // Battle feedback. Currently placeholder square-wave blips generated by
  // scripts/gen-placeholder-audio.py — drop a real {key}.webm or {key}.mp3
  // into public/audio/ and it is picked up with no code change.
  'roll_tick', 'dice_boosted', 'dice_hit', 'dice_evade', 'dice_fail',
  'impact', 'death', 'select', 'ap_short', 'tick_advance',
]

const MUSIC_KEYS: string[] = [
  // 'dungeon_theme', 'battle_theme', 'victory', 'defeat',
]

// ── State ─────────────────────────────────────────────────────────────────────

let _game:         PhaserNS.Game | null       = null
let _scene:        PhaserNS.Scene | null      = null
let _music:        PhaserNS.Sound.BaseSound | null = null
let _sfxVolume     = 0.8
let _musicVolume   = 0.5
let _ready         = false
let _initing       = false

// ── Phaser scene — loads all audio then signals ready ─────────────────────────
// Built after Phaser resolves, since it extends a runtime class.

function makeSoundScene(Phaser: typeof PhaserNS) {
  return class SoundScene extends Phaser.Scene {
    constructor() { super({ key: 'sound' }) }

    preload() {
      const base = (import.meta.env.BASE_URL ?? '/').replace(/\/$/, '') + '/'
      for (const key of [...SFX_KEYS, ...MUSIC_KEYS]) {
        // Ordered by preference — the browser takes the first format it
        // supports. .wav last so placeholder assets work until real ones land.
        this.load.audio(key, [
          `${base}audio/${key}.webm`,
          `${base}audio/${key}.mp3`,
          `${base}audio/${key}.wav`,
        ])
      }
    }

    create() {
      _scene = this
      _ready = true
    }
  }
}

// ── Public API ────────────────────────────────────────────────────────────────

export const SoundService = {
  /** Call once in App.tsx on mount. Safe to call repeatedly; resolves when the
   *  engine has booted. Audio is best-effort — a failure here must never break
   *  the app, so it is logged and swallowed. */
  async init(): Promise<void> {
    if (_game || _initing) return
    _initing = true
    try {
      const Phaser = (await import('phaser')).default
      _game = new Phaser.Game({
        type:  Phaser.HEADLESS,
        audio: { disableWebAudio: !Capacitor.isNativePlatform() && !window.AudioContext },
        scene: makeSoundScene(Phaser),
        callbacks: {
          // Suppress Phaser's "Game is now running" console banner
          postBoot: () => {},
        },
      })
    } catch (err) {
      console.warn('[SoundService] audio unavailable:', err)
    } finally {
      _initing = false
    }
  },

  playSfx(key: string, volume = _sfxVolume): void {
    if (!_ready || !_scene || !SFX_KEYS.includes(key)) return
    _scene.sound.play(key, { volume })
  },

  playMusic(key: string): void {
    if (!_ready || !_scene || !MUSIC_KEYS.includes(key)) return
    if (_music?.key === key && _music.isPlaying) return
    _music?.stop()
    _music = _scene.sound.add(key, { loop: true, volume: _musicVolume })
    _music.play()
  },

  stopMusic(): void {
    _music?.stop()
    _music = null
  },

  setSfxVolume(v: number): void {
    _sfxVolume = Math.max(0, Math.min(1, v))
  },

  setMusicVolume(v: number): void {
    _musicVolume = Math.max(0, Math.min(1, v))
    if (_music) (_music as PhaserNS.Sound.WebAudioSound).setVolume(_musicVolume)
  },

  get isReady(): boolean { return _ready },
}
